language: php

php:
  - 5.4
  - 5.5
  - 5.6

addons:
  - postgresql: "9.3"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - createuser -Upostgres -d -A -S vagrant
  - createdb -Uvagrant -E UTF-8 -T template0 app_test

script:
  - ./vendor/bin/phpunit

deploy:
  provider: heroku
  api_key: lOVeK6I0Mr5ZGMluskilo6u5ziTvPAMa7FVFPZtjOwJ3pb69lHHKZyB1fgiRRbVNAyp6ImG9J+xtxqouk5mZqukJkW3J+pRHeWHc3M8bWItrQetkZs1ErxvaxDr4CEImMolFOD6TCgdlU3LKHPfLfyPPo+FiBHag7Pi//yzVax8=
  app: laravel-table-admin
  run:
    - "php artisan migrate"
    - "php artisan db:seed"

